import type { ComparisonReport } from "@/types/domain";
import type { ResolvedBranding } from "@/lib/branding/load";
import { PDF_STYLES } from "../styles";
import type { PhotoDataUrls } from "../photos";

function escape(text: string): string {
  return text.replace(/[&<>"']/g, (c) => {
    switch (c) {
      case "&": return "&amp;";
      case "<": return "&lt;";
      case ">": return "&gt;";
      case '"': return "&quot;";
      case "'": return "&#39;";
      default: return c;
    }
  });
}

function formatVerdict(v: string): string {
  return v.replace(/_/g, " ");
}

function photoCell(dataUrl: string | undefined): string {
  if (!dataUrl) return '<span style="color: #94a3b8; font-size: 10px;">no photo</span>';
  return `<img src="${dataUrl}" alt="" style="width: 80px; height: 60px; object-fit: cover; border-radius: 4px; border: 1px solid #e2e8f0;" />`;
}

export interface ComparisonPhotos {
  checkin: PhotoDataUrls;
  checkout: PhotoDataUrls;
  refs: Record<string, { checkin?: string; checkout?: string }>; // key: "<room>::<itemName>"
}

function key(room: string, itemName: string) {
  return `${room}::${itemName}`;
}

export function buildComparisonPhotoKey(room: string, itemName: string) {
  return key(room, itemName);
}

function brandingHeader(b: ResolvedBranding | undefined): string {
  if (!b) return "";
  const businessName = b.branding.businessName || "PropertyCheck";
  const logo = b.logoDataUrl
    ? `<img src="${b.logoDataUrl}" alt="" style="height: 36px; max-width: 120px; object-fit: contain;" />`
    : "";
  return `<div style="display: flex; align-items: center; gap: 10px; margin-bottom: 6px;">
    ${logo}
    <span style="font-size: 14px; font-weight: 600; color: #475569;">${escape(businessName)}</span>
  </div>`;
}

function brandingFooter(b: ResolvedBranding | undefined): string {
  if (!b) return "Generated by PropertyCheck • Applied UK Tenant Fees Act 2019 standards";
  const parts: string[] = [escape(b.branding.businessName || "PropertyCheck")];
  if (b.branding.contactEmail) parts.push(escape(b.branding.contactEmail));
  if (b.branding.contactPhone) parts.push(escape(b.branding.contactPhone));
  if (b.branding.address) parts.push(escape(b.branding.address));
  return parts.join(" · ");
}

export function renderComparisonHtml(
  data: ComparisonReport,
  photos?: ComparisonPhotos,
  branding?: ResolvedBranding,
  inspectorName?: string
): string {
  const totalCost = data.rooms.reduce(
    (sum, room) => sum + room.items.reduce((s, i) => s + (i.estimatedCost ?? 0), 0),
    0
  );
  const fmtCost = (n: number | null) =>
    n == null ? "—" : new Intl.NumberFormat("en-GB", { style: "currency", currency: "GBP" }).format(n);

  return `<!doctype html>
<html>
<head>
<meta charset="utf-8" />
<title>Deposit Comparison Report</title>
<style>${PDF_STYLES}</style>
</head>
<body>
  <div class="header">
    ${brandingHeader(branding)}
    <h1>Deposit Comparison Report</h1>
    <div class="meta">
      <div>Property: <strong>${escape(data.propertySlug)}</strong></div>
      <div>Tenancy: <strong>${escape(data.tenancySlug)}</strong></div>
      <div>Generated: ${escape(new Date(data.generatedAt).toLocaleString("en-GB"))}</div>
      ${inspectorName ? `<div>Inspector: <strong>${escape(inspectorName)}</strong></div>` : ""}
    </div>
  </div>

  <div class="summary">
    <div class="summary-row"><span>Total items flagged</span><strong>${data.summary.totalFlagged}</strong></div>
    <div class="summary-row"><span>Tenant-liable items</span><strong>${data.summary.tenantLiableCount}</strong></div>
    <div class="summary-row"><span>Recommended deduction (est.)</span><strong>${fmtCost(totalCost)}</strong></div>
  </div>

  <h2>Recommendation</h2>
  <p>${escape(data.summary.depositRecommendation)}</p>

  ${data.rooms
    .map(
      (room) => `
    <h2>${escape(room.room)}</h2>
    <table>
      <thead>
        <tr>
          <th style="width: 12%;">Item</th>
          <th style="width: 14%;">Check-in</th>
          <th style="width: 18%;">— state —</th>
          <th style="width: 14%;">Check-out</th>
          <th style="width: 18%;">— state —</th>
          <th style="width: 10%;">Verdict</th>
          <th>Reason</th>
          <th style="width: 8%;">Cost</th>
        </tr>
      </thead>
      <tbody>
        ${room.items
          .map((item) => {
            const refs = photos?.refs[key(room.room, item.itemName)];
            const checkinPhoto = refs?.checkin ? photos?.checkin[refs.checkin] : undefined;
            const checkoutPhoto = refs?.checkout ? photos?.checkout[refs.checkout] : undefined;
            return `
          <tr>
            <td>${escape(item.itemName)}</td>
            <td>${photoCell(checkinPhoto)}</td>
            <td>${escape(item.before)}</td>
            <td>${photoCell(checkoutPhoto)}</td>
            <td>${escape(item.after)}</td>
            <td><span class="badge verdict-${escape(item.verdict)}">${escape(formatVerdict(item.verdict))}</span></td>
            <td>${escape(item.reason)}</td>
            <td>${fmtCost(item.estimatedCost)}</td>
          </tr>`;
          })
          .join("")}
      </tbody>
    </table>`
    )
    .join("")}

  <div class="footer">${brandingFooter(branding)}</div>
</body>
</html>`;
}
