import type { CheckinData } from "@/types/domain";
import type { ResolvedBranding } from "@/lib/branding/load";
import { PDF_STYLES, ratingClass } from "../styles";
import type { PhotoDataUrls } from "../photos";

function escape(text: string): string {
  return text.replace(/[&<>"']/g, (c) => {
    switch (c) {
      case "&": return "&amp;";
      case "<": return "&lt;";
      case ">": return "&gt;";
      case '"': return "&quot;";
      case "'": return "&#39;";
      default: return c;
    }
  });
}

function uniqueRoomPhotos(
  room: { items: { photoRefs: string[] }[] },
  photos: PhotoDataUrls,
  max = 4
): string[] {
  const seen = new Set<string>();
  const out: string[] = [];
  for (const item of room.items) {
    for (const ref of item.photoRefs) {
      if (out.length >= max) return out;
      if (seen.has(ref)) continue;
      seen.add(ref);
      const dataUrl = photos[ref];
      if (dataUrl) out.push(dataUrl);
    }
  }
  return out;
}

function brandingHeader(b: ResolvedBranding | undefined): string {
  if (!b) return "";
  const businessName = escape(b.branding.businessName || "PropertyCheck");
  const logo = b.logoDataUrl
    ? `<img src="${b.logoDataUrl}" alt="" style="height: 36px; max-width: 120px; object-fit: contain;" />`
    : "";
  return `<div style="display: flex; align-items: center; gap: 10px; margin-bottom: 6px;">
    ${logo}
    <span style="font-size: 14px; font-weight: 600; color: #475569;">${businessName}</span>
  </div>`;
}

function brandingFooter(b: ResolvedBranding | undefined): string {
  if (!b) return "Generated by PropertyCheck • UK Tenant Fees Act 2019 compliant";
  const parts: string[] = [escape(b.branding.businessName || "PropertyCheck")];
  if (b.branding.contactEmail) parts.push(escape(b.branding.contactEmail));
  if (b.branding.contactPhone) parts.push(escape(b.branding.contactPhone));
  if (b.branding.address) parts.push(escape(b.branding.address));
  return parts.join(" · ");
}

export function renderReportHtml(
  data: CheckinData,
  photos: PhotoDataUrls = {},
  branding?: ResolvedBranding,
  inspectorName?: string
): string {
  const title = data.kind === "checkin" ? "Check-in Inventory Report" : "Check-out Inventory Report";
  const totalItems = data.rooms.reduce((sum, r) => sum + r.items.length, 0);
  const flaggedItems = data.rooms.reduce(
    (sum, r) => sum + r.items.filter((i) => i.flagged).length,
    0
  );
  return `<!doctype html>
<html>
<head>
<meta charset="utf-8" />
<title>${escape(title)}</title>
<style>${PDF_STYLES}</style>
</head>
<body>
  <div class="header">
    ${brandingHeader(branding)}
    <h1>${escape(title)}</h1>
    <div class="meta">
      <div>Property: <strong>${escape(data.propertySlug)}</strong></div>
      <div>Tenancy: <strong>${escape(data.tenancySlug)}</strong></div>
      <div>Generated: ${escape(new Date(data.generatedAt).toLocaleString("en-GB"))}</div>
      ${inspectorName ? `<div>Inspector: <strong>${escape(inspectorName)}</strong></div>` : ""}
    </div>
  </div>

  <div class="summary">
    <div class="summary-row"><span>Rooms inspected</span><strong>${data.rooms.length}</strong></div>
    <div class="summary-row"><span>Total items</span><strong>${totalItems}</strong></div>
    <div class="summary-row"><span>Items flagged</span><strong>${flaggedItems}</strong></div>
  </div>

  ${data.rooms
    .map((room) => {
      const roomPhotos = uniqueRoomPhotos(room, photos, 4);
      const photoGrid = roomPhotos.length > 0
        ? `<div style="display: flex; flex-wrap: wrap; gap: 8px; margin: 8px 0 12px 0;">
            ${roomPhotos
              .map(
                (url) => `<img src="${url}" alt="" style="width: 160px; height: 110px; object-fit: cover; border-radius: 6px; border: 1px solid #e2e8f0;" />`
              )
              .join("")}
          </div>`
        : "";
      return `
      <h2>${escape(room.room)}</h2>
      <div class="room-note">Room confidence: ${escape(room.confidence)} · ${room.items.length} item${room.items.length === 1 ? "" : "s"}</div>
      ${photoGrid}
      <table>
        <thead>
          <tr>
            <th style="width: 28%;">Item</th>
            <th style="width: 12%;">Rating</th>
            <th>Notes</th>
          </tr>
        </thead>
        <tbody>
          ${room.items
            .map(
              (item) => `
            <tr>
              <td>${escape(item.name)}${item.flagged ? '<span class="badge badge-flag">flagged</span>' : ""}</td>
              <td><span class="badge ${ratingClass(item.rating)}">${escape(item.rating)}</span></td>
              <td>${escape(item.notes || "—")}</td>
            </tr>`
            )
            .join("")}
        </tbody>
      </table>`;
    })
    .join("")}

  <div class="footer">${brandingFooter(branding)}</div>
</body>
</html>`;
}
